-- NK Food Agro: Supabase database setup
-- Run this in Supabase SQL Editor.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  city text not null,
  state text not null,
  pincode text not null,
  landmark text default '',
  notes text default '',
  items jsonb not null,
  total numeric(12,2) not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id integer not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  rating integer not null check (rating between 1 and 5),
  review text not null check (char_length(review) between 8 and 1000),
  verified_purchase boolean not null default false,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.reviews enable row level security;

create policy "users can create their own orders" on public.orders for insert to authenticated with check (auth.uid() = user_id);
create policy "users can view their own orders" on public.orders for select to authenticated using (auth.uid() = user_id);
create policy "approved reviews are public" on public.reviews for select to anon, authenticated using (approved = true);
create policy "users can submit their own reviews" on public.reviews for insert to authenticated with check (auth.uid() = user_id);

-- Mark a review as a verified purchase when the signed-in user has an order
-- containing that product. The frontend stores product id inside orders.items.
create or replace function public.mark_verified_review()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if exists (
    select 1 from public.orders o
    where o.user_id = new.user_id
      and o.status in ('new','confirmed','delivered')
      and exists (
        select 1 from jsonb_array_elements(o.items) item
        where (item->>'id')::int = new.product_id
      )
  ) then
    new.verified_purchase := true;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_mark_verified_review on public.reviews;
create trigger trg_mark_verified_review before insert on public.reviews for each row execute function public.mark_verified_review();

-- IMPORTANT: New reviews start as approved=false. Approve genuine reviews
-- from the Supabase dashboard after checking the order/customer.
